# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'affine.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np

# initialize matrix A
A = np.zeros(6)
# initialize matrix B
B = np.zeros((6,6))
B[0:5:2, 2] = 1

class Ui_Affine(object):
    def setupUi(self, Affine):

        self.P = np.zeros(6)

        Affine.setObjectName("Affine")
        Affine.resize(960, 540)
        Affine.setMinimumSize(QtCore.QSize(960, 540))
        Affine.setMaximumSize(QtCore.QSize(960, 540))
        self.centralwidget = QtWidgets.QWidget(Affine)
        self.centralwidget.setObjectName("centralwidget")
        self.alert_icon = QtWidgets.QLabel(self.centralwidget)
        self.alert_icon.setGeometry(QtCore.QRect(40, 20, 61, 61))
        self.alert_icon.setText("")
        self.alert_icon.setPixmap(QtGui.QPixmap("images/alert-1.png"))
        self.alert_icon.setScaledContents(True)
        self.alert_icon.setObjectName("alert_icon")
        self.alert_message_label = QtWidgets.QLabel(self.centralwidget)
        self.alert_message_label.setGeometry(QtCore.QRect(110, 30, 571, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.alert_message_label.setFont(font)
        self.alert_message_label.setObjectName("alert_message_label")
        self.point_1_label = QtWidgets.QLabel(self.centralwidget)
        self.point_1_label.setGeometry(QtCore.QRect(40, 150, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.point_1_label.setFont(font)
        self.point_1_label.setObjectName("point_1_label")
        self.point_2_label = QtWidgets.QLabel(self.centralwidget)
        self.point_2_label.setGeometry(QtCore.QRect(40, 180, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.point_2_label.setFont(font)
        self.point_2_label.setObjectName("point_2_label")
        self.point_3_label = QtWidgets.QLabel(self.centralwidget)
        self.point_3_label.setGeometry(QtCore.QRect(40, 210, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.point_3_label.setFont(font)
        self.point_3_label.setObjectName("point_3_label")
        self.x_point_label = QtWidgets.QLabel(self.centralwidget)
        self.x_point_label.setGeometry(QtCore.QRect(150, 120, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.x_point_label.setFont(font)
        self.x_point_label.setAlignment(QtCore.Qt.AlignCenter)
        self.x_point_label.setObjectName("x_point_label")
        self.y_point_label = QtWidgets.QLabel(self.centralwidget)
        self.y_point_label.setGeometry(QtCore.QRect(250, 120, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.y_point_label.setFont(font)
        self.y_point_label.setAlignment(QtCore.Qt.AlignCenter)
        self.y_point_label.setObjectName("y_point_label")
        self.X_point_label = QtWidgets.QLabel(self.centralwidget)
        self.X_point_label.setGeometry(QtCore.QRect(390, 120, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.X_point_label.setFont(font)
        self.X_point_label.setAlignment(QtCore.Qt.AlignCenter)
        self.X_point_label.setObjectName("X_point_label")
        self.Y_point_label = QtWidgets.QLabel(self.centralwidget)
        self.Y_point_label.setGeometry(QtCore.QRect(490, 120, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Y_point_label.setFont(font)
        self.Y_point_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Y_point_label.setObjectName("Y_point_label")
        self.coeff_aff = QtWidgets.QPushButton(self.centralwidget)
        self.coeff_aff.setGeometry(QtCore.QRect(170, 270, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.coeff_aff.setFont(font)
        self.coeff_aff.setStyleSheet("background-color: rgb(0, 155, 134);\n"
"color: rgb(255, 255, 255);")
        self.coeff_aff.setObjectName("coeff_aff")
        self.reset_aff = QtWidgets.QPushButton(self.centralwidget)
        self.reset_aff.setGeometry(QtCore.QRect(380, 270, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.reset_aff.setFont(font)
        self.reset_aff.setStyleSheet("background-color: rgb(243, 110, 33);\n"
"color: rgb(255, 255, 255);")
        self.reset_aff.setObjectName("reset_aff")
        self.label_1_m = QtWidgets.QLabel(self.centralwidget)
        self.label_1_m.setGeometry(QtCore.QRect(60, 330, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_m.setFont(font)
        self.label_1_m.setObjectName("label_1_m")
        self.label_2_m = QtWidgets.QLabel(self.centralwidget)
        self.label_2_m.setGeometry(QtCore.QRect(40, 350, 601, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_2_m.setFont(font)
        self.label_2_m.setObjectName("label_2_m")
        self.point_m_label = QtWidgets.QLabel(self.centralwidget)
        self.point_m_label.setGeometry(QtCore.QRect(40, 420, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.point_m_label.setFont(font)
        self.point_m_label.setStyleSheet("color: rgb(242, 65, 65);")
        self.point_m_label.setObjectName("point_m_label")
        self.title_coo_ph_label = QtWidgets.QLabel(self.centralwidget)
        self.title_coo_ph_label.setGeometry(QtCore.QRect(110, 80, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.title_coo_ph_label.setFont(font)
        self.title_coo_ph_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_coo_ph_label.setObjectName("title_coo_ph_label")
        self.aff_Ym = QtWidgets.QLineEdit(self.centralwidget)
        self.aff_Ym.setGeometry(QtCore.QRect(220, 420, 81, 20))
        self.aff_Ym.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.aff_Ym.setAlignment(QtCore.Qt.AlignCenter)
        self.aff_Ym.setObjectName("aff_Ym")
        self.aff_ym = QtWidgets.QLineEdit(self.centralwidget)
        self.aff_ym.setGeometry(QtCore.QRect(460, 420, 81, 20))
        self.aff_ym.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.aff_ym.setAlignment(QtCore.Qt.AlignCenter)
        self.aff_ym.setObjectName("aff_ym")
        self.aff_xm = QtWidgets.QLineEdit(self.centralwidget)
        self.aff_xm.setGeometry(QtCore.QRect(360, 420, 81, 20))
        self.aff_xm.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.aff_xm.setAlignment(QtCore.Qt.AlignCenter)
        self.aff_xm.setObjectName("aff_xm")
        self.aff_Xm = QtWidgets.QLineEdit(self.centralwidget)
        self.aff_Xm.setGeometry(QtCore.QRect(120, 420, 81, 20))
        self.aff_Xm.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.aff_Xm.setAlignment(QtCore.Qt.AlignCenter)
        self.aff_Xm.setObjectName("aff_Xm")
        self.Y_m_label = QtWidgets.QLabel(self.centralwidget)
        self.Y_m_label.setGeometry(QtCore.QRect(250, 400, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Y_m_label.setFont(font)
        self.Y_m_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Y_m_label.setObjectName("Y_m_label")
        self.X_m_label = QtWidgets.QLabel(self.centralwidget)
        self.X_m_label.setGeometry(QtCore.QRect(150, 400, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.X_m_label.setFont(font)
        self.X_m_label.setAlignment(QtCore.Qt.AlignCenter)
        self.X_m_label.setObjectName("X_m_label")
        self.y_m_label = QtWidgets.QLabel(self.centralwidget)
        self.y_m_label.setGeometry(QtCore.QRect(490, 400, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.y_m_label.setFont(font)
        self.y_m_label.setAlignment(QtCore.Qt.AlignCenter)
        self.y_m_label.setObjectName("y_m_label")
        self.x_m_label = QtWidgets.QLabel(self.centralwidget)
        self.x_m_label.setGeometry(QtCore.QRect(390, 400, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.x_m_label.setFont(font)
        self.x_m_label.setAlignment(QtCore.Qt.AlignCenter)
        self.x_m_label.setObjectName("x_m_label")
        self.calcul_aff = QtWidgets.QPushButton(self.centralwidget)
        self.calcul_aff.setGeometry(QtCore.QRect(170, 460, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.calcul_aff.setFont(font)
        self.calcul_aff.setStyleSheet("background-color: rgb(0, 155, 134);\n"
"color: rgb(255, 255, 255);")
        self.calcul_aff.setObjectName("calcul_aff")
        self.title_trans_label = QtWidgets.QLabel(self.centralwidget)
        self.title_trans_label.setGeometry(QtCore.QRect(750, 150, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title_trans_label.setFont(font)
        self.title_trans_label.setObjectName("title_trans_label")
        self.title_proj_label = QtWidgets.QLabel(self.centralwidget)
        self.title_proj_label.setGeometry(QtCore.QRect(750, 170, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title_proj_label.setFont(font)
        self.title_proj_label.setObjectName("title_proj_label")
        self.system_img = QtWidgets.QLabel(self.centralwidget)
        self.system_img.setGeometry(QtCore.QRect(750, 200, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Playfair Display Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.system_img.setFont(font)
        self.system_img.setText("")
        self.system_img.setPixmap(QtGui.QPixmap("images/affine.png"))
        self.system_img.setScaledContents(True)
        self.system_img.setObjectName("system_img")
        self.erreur = QtWidgets.QLabel(self.centralwidget)
        self.erreur.setGeometry(QtCore.QRect(620, 410, 320, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.erreur.setFont(font)
        self.erreur.setStyleSheet("background-color: rgb(174, 188, 191);")
        self.erreur.setText("")
        self.erreur.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.erreur.setObjectName("erreur")
        self.info_icon = QtWidgets.QLabel(self.centralwidget)
        self.info_icon.setGeometry(QtCore.QRect(620, 360, 41, 41))
        self.info_icon.setText("")
        self.info_icon.setPixmap(QtGui.QPixmap("images/info-1.png"))
        self.info_icon.setScaledContents(True)
        self.info_icon.setObjectName("info_icon")
        self.title_coo_ph_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.title_coo_ph_label_2.setGeometry(QtCore.QRect(110, 100, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.title_coo_ph_label_2.setFont(font)
        self.title_coo_ph_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_coo_ph_label_2.setObjectName("title_coo_ph_label_2")
        self.title_coo_ph_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.title_coo_ph_label_3.setGeometry(QtCore.QRect(340, 100, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.title_coo_ph_label_3.setFont(font)
        self.title_coo_ph_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.title_coo_ph_label_3.setObjectName("title_coo_ph_label_3")
        self.title_coo_ph_label_4 = QtWidgets.QLabel(self.centralwidget)
        self.title_coo_ph_label_4.setGeometry(QtCore.QRect(340, 80, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.title_coo_ph_label_4.setFont(font)
        self.title_coo_ph_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.title_coo_ph_label_4.setObjectName("title_coo_ph_label_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(110, 140, 441, 101))
        self.frame.setStyleSheet("background-color: rgb(239, 168, 144);")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.aff_Y1 = QtWidgets.QLineEdit(self.frame)
        self.aff_Y1.setGeometry(QtCore.QRect(350, 10, 81, 20))
        self.aff_Y1.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.aff_Y1.setAlignment(QtCore.Qt.AlignCenter)
        self.aff_Y1.setObjectName("aff_Y1")
        self.aff_y2 = QtWidgets.QLineEdit(self.frame)
        self.aff_y2.setGeometry(QtCore.QRect(110, 40, 81, 20))
        self.aff_y2.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.aff_y2.setAlignment(QtCore.Qt.AlignCenter)
        self.aff_y2.setObjectName("aff_y2")
        self.aff_Y2 = QtWidgets.QLineEdit(self.frame)
        self.aff_Y2.setGeometry(QtCore.QRect(350, 40, 81, 20))
        self.aff_Y2.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.aff_Y2.setAlignment(QtCore.Qt.AlignCenter)
        self.aff_Y2.setObjectName("aff_Y2")
        self.aff_Y3 = QtWidgets.QLineEdit(self.frame)
        self.aff_Y3.setGeometry(QtCore.QRect(350, 70, 81, 20))
        self.aff_Y3.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.aff_Y3.setAlignment(QtCore.Qt.AlignCenter)
        self.aff_Y3.setObjectName("aff_Y3")
        self.aff_y1 = QtWidgets.QLineEdit(self.frame)
        self.aff_y1.setGeometry(QtCore.QRect(110, 10, 81, 20))
        self.aff_y1.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.aff_y1.setAlignment(QtCore.Qt.AlignCenter)
        self.aff_y1.setObjectName("aff_y1")
        self.aff_x2 = QtWidgets.QLineEdit(self.frame)
        self.aff_x2.setGeometry(QtCore.QRect(10, 40, 81, 20))
        self.aff_x2.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.aff_x2.setAlignment(QtCore.Qt.AlignCenter)
        self.aff_x2.setObjectName("aff_x2")
        self.aff_x3 = QtWidgets.QLineEdit(self.frame)
        self.aff_x3.setGeometry(QtCore.QRect(10, 70, 81, 20))
        self.aff_x3.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.aff_x3.setAlignment(QtCore.Qt.AlignCenter)
        self.aff_x3.setObjectName("aff_x3")
        self.aff_x1 = QtWidgets.QLineEdit(self.frame)
        self.aff_x1.setGeometry(QtCore.QRect(10, 10, 81, 20))
        self.aff_x1.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.aff_x1.setAlignment(QtCore.Qt.AlignCenter)
        self.aff_x1.setObjectName("aff_x1")
        self.aff_X2 = QtWidgets.QLineEdit(self.frame)
        self.aff_X2.setGeometry(QtCore.QRect(250, 40, 81, 20))
        self.aff_X2.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.aff_X2.setAlignment(QtCore.Qt.AlignCenter)
        self.aff_X2.setObjectName("aff_X2")
        self.aff_X3 = QtWidgets.QLineEdit(self.frame)
        self.aff_X3.setGeometry(QtCore.QRect(250, 70, 81, 20))
        self.aff_X3.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.aff_X3.setAlignment(QtCore.Qt.AlignCenter)
        self.aff_X3.setObjectName("aff_X3")
        self.aff_y3 = QtWidgets.QLineEdit(self.frame)
        self.aff_y3.setGeometry(QtCore.QRect(110, 70, 81, 20))
        self.aff_y3.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.aff_y3.setAlignment(QtCore.Qt.AlignCenter)
        self.aff_y3.setObjectName("aff_y3")
        self.aff_X1 = QtWidgets.QLineEdit(self.frame)
        self.aff_X1.setGeometry(QtCore.QRect(250, 10, 81, 20))
        self.aff_X1.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.aff_X1.setAlignment(QtCore.Qt.AlignCenter)
        self.aff_X1.setObjectName("aff_X1")
        self.label_c2 = QtWidgets.QLabel(self.centralwidget)
        self.label_c2.setGeometry(QtCore.QRect(640, 280, 14, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_c2.setFont(font)
        self.label_c2.setStyleSheet("color: rgb(242, 65, 65);")
        self.label_c2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_c2.setObjectName("label_c2")
        self.label_a1 = QtWidgets.QLabel(self.centralwidget)
        self.label_a1.setGeometry(QtCore.QRect(640, 120, 14, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_a1.setFont(font)
        self.label_a1.setStyleSheet("color:rgb(45, 58, 76)")
        self.label_a1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a1.setObjectName("label_a1")
        self.label_b2 = QtWidgets.QLabel(self.centralwidget)
        self.label_b2.setGeometry(QtCore.QRect(640, 250, 14, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_b2.setFont(font)
        self.label_b2.setStyleSheet("color: rgb(242, 65, 65);")
        self.label_b2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b2.setObjectName("label_b2")
        self.label_b1 = QtWidgets.QLabel(self.centralwidget)
        self.label_b1.setGeometry(QtCore.QRect(640, 150, 14, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_b1.setFont(font)
        self.label_b1.setStyleSheet("color:rgb(45, 58, 76)")
        self.label_b1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b1.setObjectName("label_b1")
        self.label_c1 = QtWidgets.QLabel(self.centralwidget)
        self.label_c1.setGeometry(QtCore.QRect(640, 180, 14, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_c1.setFont(font)
        self.label_c1.setStyleSheet("color:rgb(45, 58, 76)")
        self.label_c1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_c1.setObjectName("label_c1")
        self.label_a2 = QtWidgets.QLabel(self.centralwidget)
        self.label_a2.setGeometry(QtCore.QRect(640, 220, 14, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_a2.setFont(font)
        self.label_a2.setStyleSheet("color: rgb(242, 65, 65);")
        self.label_a2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a2.setObjectName("label_a2")
        self.a1 = QtWidgets.QLineEdit(self.centralwidget)
        self.a1.setGeometry(QtCore.QRect(670, 120, 61, 20))
        self.a1.setStyleSheet("background-color: rgb(144, 187, 243);")
        self.a1.setAlignment(QtCore.Qt.AlignCenter)
        self.a1.setObjectName("a1")
        self.a2 = QtWidgets.QLineEdit(self.centralwidget)
        self.a2.setGeometry(QtCore.QRect(670, 220, 61, 20))
        self.a2.setStyleSheet("background-color: rgb(242, 169, 169);")
        self.a2.setAlignment(QtCore.Qt.AlignCenter)
        self.a2.setObjectName("a2")
        self.b1 = QtWidgets.QLineEdit(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(670, 150, 61, 20))
        self.b1.setStyleSheet("background-color: rgb(144, 187, 243);")
        self.b1.setAlignment(QtCore.Qt.AlignCenter)
        self.b1.setObjectName("b1")
        self.d = QtWidgets.QLineEdit(self.centralwidget)
        self.d.setGeometry(QtCore.QRect(670, 280, 61, 20))
        self.d.setStyleSheet("background-color: rgb(242, 169, 169);")
        self.d.setAlignment(QtCore.Qt.AlignCenter)
        self.d.setObjectName("d")
        self.c = QtWidgets.QLineEdit(self.centralwidget)
        self.c.setGeometry(QtCore.QRect(670, 180, 61, 20))
        self.c.setStyleSheet("background-color: rgb(144, 187, 243);")
        self.c.setAlignment(QtCore.Qt.AlignCenter)
        self.c.setObjectName("c")
        self.b2 = QtWidgets.QLineEdit(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(670, 250, 61, 20))
        self.b2.setStyleSheet("background-color: rgb(242, 169, 169);")
        self.b2.setAlignment(QtCore.Qt.AlignCenter)
        self.b2.setObjectName("b2")
        self.frame.raise_()
        self.alert_icon.raise_()
        self.alert_message_label.raise_()
        self.point_1_label.raise_()
        self.point_2_label.raise_()
        self.point_3_label.raise_()
        self.x_point_label.raise_()
        self.y_point_label.raise_()
        self.X_point_label.raise_()
        self.Y_point_label.raise_()
        self.coeff_aff.raise_()
        self.reset_aff.raise_()
        self.label_1_m.raise_()
        self.label_2_m.raise_()
        self.point_m_label.raise_()
        self.title_coo_ph_label.raise_()
        self.aff_Ym.raise_()
        self.aff_ym.raise_()
        self.aff_xm.raise_()
        self.aff_Xm.raise_()
        self.Y_m_label.raise_()
        self.X_m_label.raise_()
        self.y_m_label.raise_()
        self.x_m_label.raise_()
        self.calcul_aff.raise_()
        self.title_trans_label.raise_()
        self.title_proj_label.raise_()
        self.system_img.raise_()
        self.erreur.raise_()
        self.info_icon.raise_()
        self.title_coo_ph_label_2.raise_()
        self.title_coo_ph_label_3.raise_()
        self.title_coo_ph_label_4.raise_()
        self.label_c2.raise_()
        self.label_a1.raise_()
        self.label_b2.raise_()
        self.label_b1.raise_()
        self.label_c1.raise_()
        self.label_a2.raise_()
        self.a1.raise_()
        self.a2.raise_()
        self.b1.raise_()
        self.d.raise_()
        self.c.raise_()
        self.b2.raise_()
        Affine.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Affine)
        self.statusbar.setObjectName("statusbar")
        Affine.setStatusBar(self.statusbar)
        self.Y_m_label.setBuddy(self.aff_Ym)
        self.X_m_label.setBuddy(self.aff_Xm)
        self.y_m_label.setBuddy(self.aff_ym)
        self.x_m_label.setBuddy(self.aff_xm)

        self.liste_des_cases = [self.aff_x1, self.aff_x2, self.aff_X1, self.aff_Y1, self.aff_y1, self.aff_y2,
                                self.aff_Y2, self.aff_X2, self.aff_x3, self.aff_y3, self.aff_Y3, self.aff_X3]

        self.retranslateUi(Affine)

        self.coeff_aff.clicked.connect(self.calcul_coefficents)
        self.reset_aff.clicked.connect(self.reset)
        self.calcul_aff.clicked.connect(self.caclul_pointM)

        Affine.setTabOrder(self.aff_x1, self.aff_y1)
        Affine.setTabOrder(self.aff_y1, self.aff_x2)
        Affine.setTabOrder(self.aff_x2, self.aff_y2)
        Affine.setTabOrder(self.aff_y2, self.aff_x3)
        Affine.setTabOrder(self.aff_x3, self.aff_y3)
        Affine.setTabOrder(self.aff_y3, self.aff_X1)
        Affine.setTabOrder(self.aff_X1, self.aff_Y1)
        Affine.setTabOrder(self.aff_Y1, self.aff_X2)
        Affine.setTabOrder(self.aff_X2, self.aff_Y2)
        Affine.setTabOrder(self.aff_Y2, self.aff_X3)
        Affine.setTabOrder(self.aff_X3, self.aff_Y3)
        Affine.setTabOrder(self.aff_Y3, self.coeff_aff)
        Affine.setTabOrder(self.coeff_aff, self.reset_aff)
        Affine.setTabOrder(self.reset_aff, self.aff_Xm)
        Affine.setTabOrder(self.aff_Xm, self.aff_Ym)
        Affine.setTabOrder(self.aff_Ym, self.calcul_aff)
        Affine.setTabOrder(self.calcul_aff, self.aff_xm)
        Affine.setTabOrder(self.aff_xm, self.aff_ym)
        Affine.setTabOrder(self.aff_ym, self.a1)
        Affine.setTabOrder(self.a1, self.b1)
        Affine.setTabOrder(self.b1, self.c)
        Affine.setTabOrder(self.d, self.d)
        Affine.setTabOrder(self.c, self.a2)
        Affine.setTabOrder(self.a2, self.b2)
        Affine.setTabOrder(self.b2, self.d)



    def retranslateUi(self, Affine):
        _translate = QtCore.QCoreApplication.translate
        Affine.setWindowTitle(_translate("Affine", "Transformation Affine"))
        self.alert_message_label.setText(_translate("Affine", "Il faut saisir toutes les coordonnées en mm !"))
        self.point_1_label.setText(_translate("Affine", "Point 1"))
        self.point_2_label.setText(_translate("Affine", "Point 2"))
        self.point_3_label.setText(_translate("Affine", "Point 3"))
        self.x_point_label.setText(_translate("Affine", "X"))
        self.y_point_label.setText(_translate("Affine", "Y"))
        self.X_point_label.setText(_translate("Affine", "x"))
        self.Y_point_label.setText(_translate("Affine", "y"))
        self.coeff_aff.setText(_translate("Affine", "CALCUL DES COEFFICIENTS"))
        self.reset_aff.setText(_translate("Affine", "REMETTRE A 0"))
        self.label_1_m.setText(_translate("Affine", "Après le calcul des coefficients, il suffit de saisir les coordonnées "))
        self.label_2_m.setText(_translate("Affine", "comparateurs (X, Y) d\'un point pour avoir ses coordonnées photographiques :"))
        self.point_m_label.setText(_translate("Affine", "Point M"))
        self.title_coo_ph_label.setText(_translate("Affine", "Coordonnées"))
        self.Y_m_label.setText(_translate("Affine", "Y"))
        self.X_m_label.setText(_translate("Affine", "X"))
        self.y_m_label.setText(_translate("Affine", "y"))
        self.x_m_label.setText(_translate("Affine", "x"))
        self.calcul_aff.setText(_translate("Affine", "CALCULER x ET y"))
        self.title_trans_label.setText(_translate("Affine", "Transformation"))
        self.title_proj_label.setText(_translate("Affine", "AFFINE"))
        self.title_coo_ph_label_2.setText(_translate("Affine", "comparateurs"))
        self.title_coo_ph_label_3.setText(_translate("Affine", "photographiques"))
        self.title_coo_ph_label_4.setText(_translate("Affine", "Coordonnées"))
        self.label_c2.setText(_translate("Affine", "d"))
        self.label_c2.adjustSize()
        self.label_a1.setText(_translate("Affine", "a1"))
        self.label_a1.adjustSize()
        self.label_b2.setText(_translate("Affine", "b2"))
        self.label_b2.adjustSize()
        self.label_b1.setText(_translate("Affine", "b1"))
        self.label_b1.adjustSize()
        self.label_c1.setText(_translate("Affine", "c"))
        self.label_c1.adjustSize()
        self.label_a2.setText(_translate("Affine", "a2"))
        self.label_a2.adjustSize()

    def reset(self):

        self.aff_X1.setText("")
        self.aff_Y1.setText("")
        self.aff_X2.setText("")
        self.aff_Y2.setText("")
        self.aff_X3.setText("")
        self.aff_Y3.setText("")
        self.aff_x1.setText("")
        self.aff_y1.setText("")
        self.aff_x2.setText("")
        self.aff_y2.setText("")
        self.aff_x3.setText("")
        self.aff_y3.setText("")
        self.a1.setText("")
        self.a2.setText("")
        self.b1.setText("")
        self.b2.setText("")
        self.c.setText("")
        self.d.setText("")
        self.P = np.zeros(6)
        self.aff_Xm.setText("")
        self.aff_xm.setText("")
        self.aff_Ym.setText("")
        self.aff_ym.setText("")
        self.erreur.clear()
            

    def calcul_coefficents(self):

        self.erreur.clear()
        trouve = False

        for x in self.liste_des_cases:
            if x.text() == '':
                self.erreur.setText("Il y a une ou des case vide(s)")
                trouve = True
                break

            if x.text().count('.') > 1:
                self.erreur.setText("Vous avez utilisé plusieurs points")
                trouve = True
                break

            if ',' in x.text():
                self.erreur.setText("Utilisez le . au lieu de la ,")
                trouve = True
                break

            for y in x.text():
                if not (y.isnumeric()) and y!=',' and y!='.' :
                    self.erreur.setText("Vous n'avez pas saisi des nombres ")
                    trouve = True
                    break

        if trouve:
            pass
        if not trouve:
            self.remplissage_matriceA()
            self.remplissage_matriceB()
            try:
                X1 = np.linalg.inv((B.T) @ B)
                X2 = (B.T) @ A
                self.P = X1 @ X2
                self.a1.setText('%.4f' % self.P[0])
                self.b1.setText('%.4f' % self.P[1])
                self.c.setText('%.4f' % self.P[2])
                self.a2.setText('%.4f' % self.P[3])
                self.b2.setText('%.4f' % self.P[4])
                self.d.setText('%.4f' % self.P[5])
            except:
                self.a1.setText("")
                self.a2.setText("")
                self.b1.setText("")
                self.b2.setText("")
                self.c.setText("")
                self.d.setText("")
                self.P = np.zeros(6)
                self.aff_Xm.setText("")
                self.aff_xm.setText("")
                self.aff_Ym.setText("")
                self.aff_ym.setText("")
                self.erreur.setText("La transformation est invalide !")

    def caclul_pointM(self):

        trouve = False
        self.erreur.clear()

        if self.aff_Xm.text() == '' or self.aff_Ym.text() == '':
            self.erreur.setText("L'une des cases est vide!")
            trouve = True
        if (',' in self.aff_Xm.text()) or (',' in self.aff_Ym.text()):
            self.erreur.setText("Vous avez utilisé plusieurs points ")
            trouve = True
        if (self.aff_Xm.text().count('.') > 1) or (self.aff_Ym.text().count('.') > 1):
            self.erreur.setText("Utilisez le . au lieu de la , ")
            trouve = True
        for x in self.aff_Xm.text():
            if x.isalpha():
                self.erreur.setText("Vous avez saisi des lettres !")
                trouve = True
                break

        for x in self.aff_Ym.text():
            if x.isalpha():
                self.erreur.setText("Vous avez saisi des lettres !")
                trouve = True
                break

        if not (trouve):
            
            temp = (self.P== np.zeros(6).all())
            if temp.all():
                self.erreur.setText("Il faut calculer les coefficients")
            else:
                x = self.P[0] * float(self.aff_Xm.text()) + self.P[1] * float(self.aff_Ym.text()) + self.P[2]
                y = self.P[3] * float(self.aff_Xm.text()) + self.P[4] * float(self.aff_Ym.text()) + self.P[5]
                self.aff_xm.setText('%.2f' % x)
                self.aff_ym.setText('%.2f' % y)
        
    def remplissage_matriceA(self):

        A[0] = float(self.aff_X1.text())
        A[1] = float(self.aff_Y1.text())
        A[2] = float(self.aff_X2.text())
        A[3] = float(self.aff_Y2.text())
        A[4] = float(self.aff_X3.text())
        A[-1] = float(self.aff_Y3.text())

    def remplissage_matriceB(self):

        B[0, :2] = [float(self.aff_x1.text()), float(self.aff_y1.text())]  # remplissage de 1e ligne
        B[2, :2] = [float(self.aff_x2.text()), float(self.aff_y2.text())]  # remplissage de 3e ligne
        B[4, :2] = [float(self.aff_x3.text()), float(self.aff_y3.text())]  # remplissage de 5e ligne
        for i in range(0, 5, 2):  # remplissage des autres lignes
            B[i + 1, 3:] = B[i, :3]

