from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np

# initialisation de la matrice A
A = np.zeros(4)

# initialisation de la matrice B
B = np.eye(4)
B[:2] = B[2:]

class Ui_Helmert(object):
    def setupUi(self, Helmert):

        self.P = np.zeros(4)

        Helmert.setObjectName("Helmert")
        Helmert.resize(960, 540)
        Helmert.setMinimumSize(QtCore.QSize(960, 540))
        Helmert.setMaximumSize(QtCore.QSize(960, 540))
        self.centralwidget = QtWidgets.QWidget(Helmert)
        self.centralwidget.setObjectName("centralwidget")
        self.alert_icon = QtWidgets.QLabel(self.centralwidget)
        self.alert_icon.setGeometry(QtCore.QRect(40, 40, 61, 61))
        self.alert_icon.setText("")
        self.alert_icon.setPixmap(QtGui.QPixmap("images/alert-1.png"))
        self.alert_icon.setScaledContents(True)
        self.alert_icon.setObjectName("alert_icon")
        self.alert_message_label = QtWidgets.QLabel(self.centralwidget)
        self.alert_message_label.setGeometry(QtCore.QRect(110, 50, 571, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.alert_message_label.setFont(font)
        self.alert_message_label.setObjectName("alert_message_label")
        self.point_1_label = QtWidgets.QLabel(self.centralwidget)
        self.point_1_label.setGeometry(QtCore.QRect(40, 170, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.point_1_label.setFont(font)
        self.point_1_label.setObjectName("point_1_label")
        self.point_2_label = QtWidgets.QLabel(self.centralwidget)
        self.point_2_label.setGeometry(QtCore.QRect(40, 200, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.point_2_label.setFont(font)
        self.point_2_label.setObjectName("point_2_label")
        self.x_point_label = QtWidgets.QLabel(self.centralwidget)
        self.x_point_label.setGeometry(QtCore.QRect(150, 140, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.x_point_label.setFont(font)
        self.x_point_label.setAlignment(QtCore.Qt.AlignCenter)
        self.x_point_label.setObjectName("x_point_label")
        self.y_point_label = QtWidgets.QLabel(self.centralwidget)
        self.y_point_label.setGeometry(QtCore.QRect(250, 140, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.y_point_label.setFont(font)
        self.y_point_label.setAlignment(QtCore.Qt.AlignCenter)
        self.y_point_label.setObjectName("y_point_label")
        self.X_point_label = QtWidgets.QLabel(self.centralwidget)
        self.X_point_label.setGeometry(QtCore.QRect(390, 140, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.X_point_label.setFont(font)
        self.X_point_label.setAlignment(QtCore.Qt.AlignCenter)
        self.X_point_label.setObjectName("X_point_label")
        self.Y_point_label = QtWidgets.QLabel(self.centralwidget)
        self.Y_point_label.setGeometry(QtCore.QRect(490, 140, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Y_point_label.setFont(font)
        self.Y_point_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Y_point_label.setObjectName("Y_point_label")
        self.coeff_helmert = QtWidgets.QPushButton(self.centralwidget)
        self.coeff_helmert.setGeometry(QtCore.QRect(170, 270, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.coeff_helmert.setFont(font)
        self.coeff_helmert.setStyleSheet("background-color: rgb(0, 155, 134);\n"
"color: rgb(255, 255, 255);")
        self.coeff_helmert.setObjectName("coeff_helmert")
        self.reset_helmert = QtWidgets.QPushButton(self.centralwidget)
        self.reset_helmert.setGeometry(QtCore.QRect(380, 270, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.reset_helmert.setFont(font)
        self.reset_helmert.setStyleSheet("background-color: rgb(243, 110, 33);\n"
"color: rgb(255, 255, 255);")
        self.reset_helmert.setObjectName("reset_helmert")
        self.label_1_m = QtWidgets.QLabel(self.centralwidget)
        self.label_1_m.setGeometry(QtCore.QRect(60, 330, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_m.setFont(font)
        self.label_1_m.setObjectName("label_1_m")
        self.label_2_m = QtWidgets.QLabel(self.centralwidget)
        self.label_2_m.setGeometry(QtCore.QRect(40, 350, 601, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_2_m.setFont(font)
        self.label_2_m.setObjectName("label_2_m")
        self.point_m_label = QtWidgets.QLabel(self.centralwidget)
        self.point_m_label.setGeometry(QtCore.QRect(40, 420, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.point_m_label.setFont(font)
        self.point_m_label.setStyleSheet("color: rgb(242, 65, 65);")
        self.point_m_label.setObjectName("point_m_label")
        self.title_coo_ph_label = QtWidgets.QLabel(self.centralwidget)
        self.title_coo_ph_label.setGeometry(QtCore.QRect(110, 100, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.title_coo_ph_label.setFont(font)
        self.title_coo_ph_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_coo_ph_label.setObjectName("title_coo_ph_label")
        self.hel_Ym = QtWidgets.QLineEdit(self.centralwidget)
        self.hel_Ym.setGeometry(QtCore.QRect(220, 420, 81, 20))
        self.hel_Ym.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.hel_Ym.setAlignment(QtCore.Qt.AlignCenter)
        self.hel_Ym.setObjectName("hel_Ym")
        self.hel_ym = QtWidgets.QLineEdit(self.centralwidget)
        self.hel_ym.setGeometry(QtCore.QRect(460, 420, 81, 20))
        self.hel_ym.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.hel_ym.setAlignment(QtCore.Qt.AlignCenter)
        self.hel_ym.setObjectName("hel_ym")
        self.hel_xm = QtWidgets.QLineEdit(self.centralwidget)
        self.hel_xm.setGeometry(QtCore.QRect(360, 420, 81, 20))
        self.hel_xm.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.hel_xm.setAlignment(QtCore.Qt.AlignCenter)
        self.hel_xm.setObjectName("hel_xm")
        self.hel_Xm = QtWidgets.QLineEdit(self.centralwidget)
        self.hel_Xm.setGeometry(QtCore.QRect(120, 420, 81, 20))
        self.hel_Xm.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.hel_Xm.setAlignment(QtCore.Qt.AlignCenter)
        self.hel_Xm.setObjectName("hel_Xm")
        self.Y_m_label = QtWidgets.QLabel(self.centralwidget)
        self.Y_m_label.setGeometry(QtCore.QRect(250, 400, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Y_m_label.setFont(font)
        self.Y_m_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Y_m_label.setObjectName("Y_m_label")
        self.X_m_label = QtWidgets.QLabel(self.centralwidget)
        self.X_m_label.setGeometry(QtCore.QRect(150, 400, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.X_m_label.setFont(font)
        self.X_m_label.setAlignment(QtCore.Qt.AlignCenter)
        self.X_m_label.setObjectName("X_m_label")
        self.y_m_label = QtWidgets.QLabel(self.centralwidget)
        self.y_m_label.setGeometry(QtCore.QRect(490, 400, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.y_m_label.setFont(font)
        self.y_m_label.setAlignment(QtCore.Qt.AlignCenter)
        self.y_m_label.setObjectName("y_m_label")
        self.x_m_label = QtWidgets.QLabel(self.centralwidget)
        self.x_m_label.setGeometry(QtCore.QRect(390, 400, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.x_m_label.setFont(font)
        self.x_m_label.setAlignment(QtCore.Qt.AlignCenter)
        self.x_m_label.setObjectName("x_m_label")
        self.calcul_helmert = QtWidgets.QPushButton(self.centralwidget)
        self.calcul_helmert.setGeometry(QtCore.QRect(170, 460, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.calcul_helmert.setFont(font)
        self.calcul_helmert.setStyleSheet("background-color: rgb(0, 155, 134);\n"
"color: rgb(255, 255, 255);")
        self.calcul_helmert.setObjectName("calcul_helmert")
        self.title_trans_label = QtWidgets.QLabel(self.centralwidget)
        self.title_trans_label.setGeometry(QtCore.QRect(750, 150, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title_trans_label.setFont(font)
        self.title_trans_label.setObjectName("title_trans_label")
        self.title_proj_label = QtWidgets.QLabel(self.centralwidget)
        self.title_proj_label.setGeometry(QtCore.QRect(750, 170, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title_proj_label.setFont(font)
        self.title_proj_label.setObjectName("title_proj_label")
        self.system_img = QtWidgets.QLabel(self.centralwidget)
        self.system_img.setGeometry(QtCore.QRect(750, 200, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Playfair Display Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.system_img.setFont(font)
        self.system_img.setText("")
        self.system_img.setPixmap(QtGui.QPixmap("images/helmert.png"))
        self.system_img.setScaledContents(True)
        self.system_img.setObjectName("system_img")
        self.erreur_hel = QtWidgets.QLabel(self.centralwidget)
        self.erreur_hel.setGeometry(QtCore.QRect(620, 410, 320, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.erreur_hel.setFont(font)
        self.erreur_hel.setStyleSheet("background-color: rgb(174, 188, 191);")
        self.erreur_hel.setText("")
        self.erreur_hel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.erreur_hel.setObjectName("erreur_hel")
        self.info_icon = QtWidgets.QLabel(self.centralwidget)
        self.info_icon.setGeometry(QtCore.QRect(620, 360, 41, 41))
        self.info_icon.setText("")
        self.info_icon.setPixmap(QtGui.QPixmap("images/info-1.png"))
        self.info_icon.setScaledContents(True)
        self.info_icon.setObjectName("info_icon")
        self.title_coo_ph_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.title_coo_ph_label_2.setGeometry(QtCore.QRect(110, 120, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.title_coo_ph_label_2.setFont(font)
        self.title_coo_ph_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_coo_ph_label_2.setObjectName("title_coo_ph_label_2")
        self.title_coo_ph_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.title_coo_ph_label_3.setGeometry(QtCore.QRect(340, 120, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.title_coo_ph_label_3.setFont(font)
        self.title_coo_ph_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.title_coo_ph_label_3.setObjectName("title_coo_ph_label_3")
        self.title_coo_ph_label_4 = QtWidgets.QLabel(self.centralwidget)
        self.title_coo_ph_label_4.setGeometry(QtCore.QRect(340, 100, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.title_coo_ph_label_4.setFont(font)
        self.title_coo_ph_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.title_coo_ph_label_4.setObjectName("title_coo_ph_label_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(110, 160, 441, 71))
        self.frame.setStyleSheet("background-color: rgb(239, 168, 144);")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.hel_Y1 = QtWidgets.QLineEdit(self.frame)
        self.hel_Y1.setGeometry(QtCore.QRect(350, 10, 81, 20))
        self.hel_Y1.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.hel_Y1.setAlignment(QtCore.Qt.AlignCenter)
        self.hel_Y1.setObjectName("hel_Y1")
        self.hel_y2 = QtWidgets.QLineEdit(self.frame)
        self.hel_y2.setGeometry(QtCore.QRect(110, 40, 81, 20))
        self.hel_y2.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.hel_y2.setAlignment(QtCore.Qt.AlignCenter)
        self.hel_y2.setObjectName("hel_y2")
        self.hel_Y2 = QtWidgets.QLineEdit(self.frame)
        self.hel_Y2.setGeometry(QtCore.QRect(350, 40, 81, 20))
        self.hel_Y2.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.hel_Y2.setAlignment(QtCore.Qt.AlignCenter)
        self.hel_Y2.setObjectName("hel_Y2")
        self.hel_y1 = QtWidgets.QLineEdit(self.frame)
        self.hel_y1.setGeometry(QtCore.QRect(110, 10, 81, 20))
        self.hel_y1.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.hel_y1.setAlignment(QtCore.Qt.AlignCenter)
        self.hel_y1.setObjectName("hel_y1")
        self.hel_x2 = QtWidgets.QLineEdit(self.frame)
        self.hel_x2.setGeometry(QtCore.QRect(10, 40, 81, 20))
        self.hel_x2.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.hel_x2.setAlignment(QtCore.Qt.AlignCenter)
        self.hel_x2.setObjectName("hel_x2")
        self.hel_x1 = QtWidgets.QLineEdit(self.frame)
        self.hel_x1.setGeometry(QtCore.QRect(10, 10, 81, 20))
        self.hel_x1.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.hel_x1.setAlignment(QtCore.Qt.AlignCenter)
        self.hel_x1.setObjectName("hel_x1")
        self.hel_X2 = QtWidgets.QLineEdit(self.frame)
        self.hel_X2.setGeometry(QtCore.QRect(250, 40, 81, 20))
        self.hel_X2.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.hel_X2.setAlignment(QtCore.Qt.AlignCenter)
        self.hel_X2.setObjectName("hel_X2")
        self.hel_X1 = QtWidgets.QLineEdit(self.frame)
        self.hel_X1.setGeometry(QtCore.QRect(250, 10, 81, 20))
        self.hel_X1.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.hel_X1.setAlignment(QtCore.Qt.AlignCenter)
        self.hel_X1.setObjectName("hel_X1")
        self.label_c2 = QtWidgets.QLabel(self.centralwidget)
        self.label_c2.setGeometry(QtCore.QRect(640, 260, 14, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_c2.setFont(font)
        self.label_c2.setStyleSheet("color: rgb(242, 65, 65);")
        self.label_c2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_c2.setObjectName("label_c2")
        self.label_a1 = QtWidgets.QLabel(self.centralwidget)
        self.label_a1.setGeometry(QtCore.QRect(640, 150, 14, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_a1.setFont(font)
        self.label_a1.setStyleSheet("color:rgb(45, 58, 76)")
        self.label_a1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a1.setObjectName("label_a1")
        self.label_b2 = QtWidgets.QLabel(self.centralwidget)
        self.label_b2.setGeometry(QtCore.QRect(640, 230, 14, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_b2.setFont(font)
        self.label_b2.setStyleSheet("color: rgb(242, 65, 65);")
        self.label_b2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b2.setObjectName("label_b2")
        self.label_b1 = QtWidgets.QLabel(self.centralwidget)
        self.label_b1.setGeometry(QtCore.QRect(640, 180, 14, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_b1.setFont(font)
        self.label_b1.setStyleSheet("color:rgb(45, 58, 76)")
        self.label_b1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b1.setObjectName("label_b1")
        self.a_helm = QtWidgets.QLineEdit(self.centralwidget)
        self.a_helm.setGeometry(QtCore.QRect(670, 150, 61, 20))
        self.a_helm.setStyleSheet("background-color: rgb(144, 187, 243);")
        self.a_helm.setAlignment(QtCore.Qt.AlignCenter)
        self.a_helm.setObjectName("a_helm")
        self.b_helm = QtWidgets.QLineEdit(self.centralwidget)
        self.b_helm.setGeometry(QtCore.QRect(670, 180, 61, 20))
        self.b_helm.setStyleSheet("background-color: rgb(144, 187, 243);")
        self.b_helm.setAlignment(QtCore.Qt.AlignCenter)
        self.b_helm.setObjectName("b_helm")
        self.d_helm = QtWidgets.QLineEdit(self.centralwidget)
        self.d_helm.setGeometry(QtCore.QRect(670, 260, 61, 20))
        self.d_helm.setStyleSheet("background-color: rgb(242, 169, 169);")
        self.d_helm.setAlignment(QtCore.Qt.AlignCenter)
        self.d_helm.setObjectName("d_helm")
        self.c_helm = QtWidgets.QLineEdit(self.centralwidget)
        self.c_helm.setGeometry(QtCore.QRect(670, 230, 61, 20))
        self.c_helm.setStyleSheet("background-color: rgb(242, 169, 169);")
        self.c_helm.setAlignment(QtCore.Qt.AlignCenter)
        self.c_helm.setObjectName("c_helm")
        self.frame.raise_()
        self.alert_icon.raise_()
        self.alert_message_label.raise_()
        self.point_1_label.raise_()
        self.point_2_label.raise_()
        self.x_point_label.raise_()
        self.y_point_label.raise_()
        self.X_point_label.raise_()
        self.Y_point_label.raise_()
        self.coeff_helmert.raise_()
        self.reset_helmert.raise_()
        self.label_1_m.raise_()
        self.label_2_m.raise_()
        self.point_m_label.raise_()
        self.title_coo_ph_label.raise_()
        self.hel_Ym.raise_()
        self.hel_ym.raise_()
        self.hel_xm.raise_()
        self.hel_Xm.raise_()
        self.Y_m_label.raise_()
        self.X_m_label.raise_()
        self.y_m_label.raise_()
        self.x_m_label.raise_()
        self.calcul_helmert.raise_()
        self.title_trans_label.raise_()
        self.title_proj_label.raise_()
        self.system_img.raise_()
        self.erreur_hel.raise_()
        self.info_icon.raise_()
        self.title_coo_ph_label_2.raise_()
        self.title_coo_ph_label_3.raise_()
        self.title_coo_ph_label_4.raise_()
        self.label_c2.raise_()
        self.label_a1.raise_()
        self.label_b2.raise_()
        self.label_b1.raise_()
        self.a_helm.raise_()
        self.b_helm.raise_()
        self.d_helm.raise_()
        self.c_helm.raise_()
        Helmert.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Helmert)
        self.statusbar.setObjectName("statusbar")
        Helmert.setStatusBar(self.statusbar)
        self.Y_m_label.setBuddy(self.hel_Ym)
        self.X_m_label.setBuddy(self.hel_Xm)
        self.y_m_label.setBuddy(self.hel_ym)
        self.x_m_label.setBuddy(self.hel_xm)

        self.liste_des_cases = [self.hel_x1, self.hel_x2, self.hel_X1, self.hel_Y1, self.hel_y1, self.hel_y2,
                                self.hel_Y2, self.hel_X2]

        self.retranslateUi(Helmert)
        # self.reset_helmert.clicked.connect(self.hel_x1.clear)
        # self.reset_helmert.clicked.connect(self.hel_y1.clear)
        # self.reset_helmert.clicked.connect(self.hel_x2.clear)
        # self.reset_helmert.clicked.connect(self.hel_y2.clear)
        # self.reset_helmert.clicked.connect(self.hel_X1.clear)
        # self.reset_helmert.clicked.connect(self.hel_Y1.clear)
        # self.reset_helmert.clicked.connect(self.hel_X2.clear)
        # self.reset_helmert.clicked.connect(self.hel_Y2.clear)
        # self.reset_helmert.clicked.connect(self.hel_Xm.clear)
        # self.reset_helmert.clicked.connect(self.hel_Ym.clear)
        # self.reset_helmert.clicked.connect(self.hel_xm.clear)
        # self.reset_helmert.clicked.connect(self.hel_ym.clear)
        # QtCore.QMetaObject.connectSlotsByName(Helmert)
        Helmert.setTabOrder(self.hel_x1, self.hel_y1)
        Helmert.setTabOrder(self.hel_y1, self.hel_x2)
        Helmert.setTabOrder(self.hel_x2, self.hel_y2)
        Helmert.setTabOrder(self.hel_y2, self.hel_X1)
        Helmert.setTabOrder(self.hel_X1, self.hel_Y1)
        Helmert.setTabOrder(self.hel_Y1, self.hel_X2)
        Helmert.setTabOrder(self.hel_X2, self.hel_Y2)
        Helmert.setTabOrder(self.hel_Y2, self.coeff_helmert)
        Helmert.setTabOrder(self.coeff_helmert, self.reset_helmert)
        Helmert.setTabOrder(self.reset_helmert, self.hel_Xm)
        Helmert.setTabOrder(self.hel_Xm, self.hel_Ym)
        Helmert.setTabOrder(self.hel_Ym, self.calcul_helmert)
        Helmert.setTabOrder(self.calcul_helmert, self.hel_xm)
        Helmert.setTabOrder(self.hel_xm, self.hel_ym)
        Helmert.setTabOrder(self.hel_ym, self.a_helm)
        Helmert.setTabOrder(self.a_helm, self.b_helm)
        Helmert.setTabOrder(self.b_helm, self.c_helm)
        Helmert.setTabOrder(self.c_helm, self.d_helm)

        self.coeff_helmert.clicked.connect(self.calcul_coefficents)  # fonction lors du clic sur le bouton vert "calculer les coefficients"
        self.reset_helmert.clicked.connect(self.reset)  # fonction lors du clic sur le bouton rouge "remettre à 0"
        self.calcul_helmert.clicked.connect(self.calcul_pointM)  # fonction lors du clic sur le bouton vert "calculer X,Y"

    def retranslateUi(self, Helmert):
        _translate = QtCore.QCoreApplication.translate
        Helmert.setWindowTitle(_translate("Helmert", "Transformation Helmert"))
        self.alert_message_label.setText(_translate("Helmert", "Il faut saisir toutes les coordonnées en mm !"))
        self.point_1_label.setText(_translate("Helmert", "Point 1"))
        self.point_2_label.setText(_translate("Helmert", "Point 2"))
        self.x_point_label.setText(_translate("Helmert", "X"))
        self.y_point_label.setText(_translate("Helmert", "Y"))
        self.X_point_label.setText(_translate("Helmert", "x"))
        self.Y_point_label.setText(_translate("Helmert", "y"))
        self.coeff_helmert.setText(_translate("Helmert", "CALCUL DES COEFFICIENTS"))
        self.reset_helmert.setText(_translate("Helmert", "REMETTRE A 0"))
        self.label_1_m.setText(_translate("Helmert", "Après le calcul des coefficients, il suffit de saisir les coordonnées "))
        self.label_2_m.setText(_translate("Helmert", "comparateurs (X, Y) d\'un point pour avoir ses coordonnées photographiques :"))
        self.point_m_label.setText(_translate("Helmert", "Point M"))
        self.title_coo_ph_label.setText(_translate("Helmert", "Coordonnées"))
        self.Y_m_label.setText(_translate("Helmert", "Y"))
        self.X_m_label.setText(_translate("Helmert", "X"))
        self.y_m_label.setText(_translate("Helmert", "y"))
        self.x_m_label.setText(_translate("Helmert", "x"))
        self.calcul_helmert.setText(_translate("Helmert", "CALCULER x ET y"))
        self.title_trans_label.setText(_translate("Helmert", "Transformation"))
        self.title_proj_label.setText(_translate("Helmert", "HELMERT"))
        self.title_coo_ph_label_2.setText(_translate("Helmert", "comparateurs"))
        self.title_coo_ph_label_3.setText(_translate("Helmert", "photographiques"))
        self.title_coo_ph_label_4.setText(_translate("Helmert", "Coordonnées"))
        self.label_c2.setText(_translate("Helmert", "d"))
        self.label_a1.setText(_translate("Helmert", "a"))
        self.label_b2.setText(_translate("Helmert", "c"))
        self.label_b1.setText(_translate("Helmert", "b"))

    def reset(self):  # pour le bouton rouge de remise a 0

        self.hel_X1.setText("")
        self.hel_Y1.setText("")
        self.hel_X2.setText("")
        self.hel_Y2.setText("")
        self.hel_x1.setText("")
        self.hel_y1.setText("")
        self.hel_x2.setText("")
        self.hel_y2.setText("")
        self.a_helm.setText("")
        self.b_helm.setText("")
        self.c_helm.setText('')
        self.d_helm.setText("")
        self.P = np.zeros(4)
        self.hel_Xm.setText("")
        self.hel_xm.setText("")
        self.hel_Ym.setText("")
        self.hel_ym.setText("")
        self.erreur_hel.clear()

    def calcul_coefficents(self):  # pour le bouton vert de calcul de coefficients
        self.erreur_hel.setText("")  # dispararition dyal message d'erreur
        trouve = False  # jusqu'a present pas d'erreur
        for x in self.liste_des_cases:
            if x.text() == '':
                self.erreur_hel.setText("Il y a une ou des case vide(s)")
                trouve = True
                break

            if x.text().count('.') > 1:
                self.erreur_hel.setText("Vous avez utilisé plusieurs points")
                trouve = True
                break

            if ',' in x.text():  # si une case contient un nombre décimal avec , et non .
                self.erreur_hel.setText("Utilisez le . au lieu de la , ")
                trouve = True
                break

            for y in x.text():  # s'il y a au moins une lettre saisie
                if not (y.isnumeric()) and y!=',' and y!='.' :
                    self.erreur_hel.setText("Vous n'avez pas saisi des nombres ")
                    trouve = True
                    break

        if trouve:
            pass
        else:
            self.remplissage_matriceA()
            self.remplissage_matriceB()
            try:

                X1 = np.linalg.inv((B.T) @ B)  # produit matriciel de B et de sa transposée:
                X2 = (B.T) @ A  # produit matriciel de la transposée de B et de A
                self.P = X1 @ X2  # les coefficients qu'on cherche
                self.a_helm.setText('%.4f' % self.P[0])
                self.b_helm.setText('%.4f' % self.P[1])
                self.c_helm.setText('%.4f' % self.P[2])
                self.d_helm.setText('%.4f' % self.P[3])
            except:
                self.a_helm.setText("")
                self.b_helm.setText("")
                self.c_helm.setText('')
                self.d_helm.setText("")
                
                self.P = np.zeros(4)
                self.erreur_hel.setText(
                    "La transformation est invalide !")

    def calcul_pointM(self):  # pour le bouton vert de calcul de X,Y
        

        trouve = False
        self.erreur_hel.setText("")

        if (self.hel_Xm.text() == '') or (self.hel_Ym.text() == ''):
            self.erreur_hel.setText("L'une des cases est vide!")
            trouve = True
        if (',' in self.hel_Xm.text()) or (',' in self.hel_Ym.text()):
            self.erreur_hel.setText("Vous avez utilisé plusieurs points ")
            trouve = True
        if (self.hel_Xm.text().count('.') > 1) or (self.hel_Ym.text().count('.') > 1):
            self.erreur_hel.setText("Utilisez le . au lieu de la , ")
            trouve = True
        for x in self.hel_Xm.text():
            if x.isalpha():
                self.erreur_hel.setText("Vous avez saisi des lettres !")
                trouve = True
                break

        for x in self.hel_Ym.text():
            if x.isalpha():
                self.erreur_hel.setText("Vous avez saisi des lettres !")
                trouve = True
                break

        
        if not(trouve) :
            temp = (self.P== np.zeros(4).all())
            if temp.all():
                self.erreur_hel.setText("Il faut calculer les coefficients")
            else :

                X = self.P[0]*float(self.hel_Xm.text()) - self.P[1]*float(self.hel_Ym.text()) + self.P[2]   
                Y = self.P[1]*float(self.hel_Xm.text()) + self.P[0]*float(self.hel_Ym.text()) + self.P[-1]
                self.hel_xm.setText('%.2f' % X)
                self.hel_ym.setText('%.2f' % Y)



    def remplissage_matriceA(self):

        A[0] = float(self.hel_X1.text())
        A[1] = float(self.hel_Y1.text())
        A[2] = float(self.hel_X2.text())
        A[-1] = float(self.hel_Y2.text())

    def remplissage_matriceB(self):

        B[:, 0] = [float(self.hel_x1.text()), float(self.hel_y1.text()), float(self.hel_x2.text()),
                   float(self.hel_y2.text())]  # remplissage de 1e colonne
        B[:, 1] = [-float(self.hel_y1.text()), float(self.hel_x1.text()), -float(self.hel_y2.text()),
                   float(self.hel_x2.text())]  # remplissage de 2e colonne



