# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projective.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np

# initialize matrix A
A = np.zeros(8)

# initialize matrix B
B = np.zeros((8, 8))
ones = np.array([[1], [1], [1], [1]])
B[:4, [2]] = B[4:, [5]] = ones

class Ui_Projective(object):
    def setupUi(self, Projective):

        # initialize matrix P
        self.P = np.zeros(8)

        Projective.setObjectName("Projective")
        Projective.resize(960, 540)
        Projective.setMinimumSize(QtCore.QSize(960, 540))
        Projective.setMaximumSize(QtCore.QSize(960, 540))
        self.centralwidget = QtWidgets.QWidget(Projective)
        self.centralwidget.setObjectName("centralwidget")
        self.alert_icon = QtWidgets.QLabel(self.centralwidget)
        self.alert_icon.setGeometry(QtCore.QRect(40, 20, 61, 61))
        self.alert_icon.setText("")
        self.alert_icon.setPixmap(QtGui.QPixmap("images/alert-1.png"))
        self.alert_icon.setScaledContents(True)
        self.alert_icon.setObjectName("alert_icon")
        self.alert_message_label = QtWidgets.QLabel(self.centralwidget)
        self.alert_message_label.setGeometry(QtCore.QRect(110, 30, 571, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.alert_message_label.setFont(font)
        self.alert_message_label.setObjectName("alert_message_label")
        self.point_1_label = QtWidgets.QLabel(self.centralwidget)
        self.point_1_label.setGeometry(QtCore.QRect(40, 140, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.point_1_label.setFont(font)
        self.point_1_label.setObjectName("point_1_label")
        self.point_2_label = QtWidgets.QLabel(self.centralwidget)
        self.point_2_label.setGeometry(QtCore.QRect(40, 170, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.point_2_label.setFont(font)
        self.point_2_label.setObjectName("point_2_label")
        self.point_3_label = QtWidgets.QLabel(self.centralwidget)
        self.point_3_label.setGeometry(QtCore.QRect(40, 200, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.point_3_label.setFont(font)
        self.point_3_label.setObjectName("point_3_label")
        self.point_4_label = QtWidgets.QLabel(self.centralwidget)
        self.point_4_label.setGeometry(QtCore.QRect(40, 230, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.point_4_label.setFont(font)
        self.point_4_label.setObjectName("point_4_label")
        self.x_point_label = QtWidgets.QLabel(self.centralwidget)
        self.x_point_label.setGeometry(QtCore.QRect(150, 110, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.x_point_label.setFont(font)
        self.x_point_label.setAlignment(QtCore.Qt.AlignCenter)
        self.x_point_label.setObjectName("x_point_label")
        self.y_point_label = QtWidgets.QLabel(self.centralwidget)
        self.y_point_label.setGeometry(QtCore.QRect(250, 110, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.y_point_label.setFont(font)
        self.y_point_label.setAlignment(QtCore.Qt.AlignCenter)
        self.y_point_label.setObjectName("y_point_label")
        self.X_point_label = QtWidgets.QLabel(self.centralwidget)
        self.X_point_label.setGeometry(QtCore.QRect(390, 110, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.X_point_label.setFont(font)
        self.X_point_label.setAlignment(QtCore.Qt.AlignCenter)
        self.X_point_label.setObjectName("X_point_label")
        self.Y_point_label = QtWidgets.QLabel(self.centralwidget)
        self.Y_point_label.setGeometry(QtCore.QRect(490, 110, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Y_point_label.setFont(font)
        self.Y_point_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Y_point_label.setObjectName("Y_point_label")
        self.btn_calcul_coef = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calcul_coef.setGeometry(QtCore.QRect(170, 270, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_calcul_coef.setFont(font)
        self.btn_calcul_coef.setStyleSheet("background-color: rgb(0, 155, 134);\n"
"color: rgb(255, 255, 255);")
        self.btn_calcul_coef.setObjectName("btn_calcul_coef")
        self.btn_remettre = QtWidgets.QPushButton(self.centralwidget)
        self.btn_remettre.setGeometry(QtCore.QRect(380, 270, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_remettre.setFont(font)
        self.btn_remettre.setStyleSheet("background-color: rgb(243, 110, 33);\n"
"color: rgb(255, 255, 255);")
        self.btn_remettre.setObjectName("btn_remettre")
        self.label_1_m = QtWidgets.QLabel(self.centralwidget)
        self.label_1_m.setGeometry(QtCore.QRect(60, 330, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_m.setFont(font)
        self.label_1_m.setObjectName("label_1_m")
        self.label_2_m = QtWidgets.QLabel(self.centralwidget)
        self.label_2_m.setGeometry(QtCore.QRect(40, 350, 601, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_2_m.setFont(font)
        self.label_2_m.setObjectName("label_2_m")
        self.point_m_label = QtWidgets.QLabel(self.centralwidget)
        self.point_m_label.setGeometry(QtCore.QRect(40, 420, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.point_m_label.setFont(font)
        self.point_m_label.setStyleSheet("color: rgb(242, 65, 65);")
        self.point_m_label.setObjectName("point_m_label")
        self.title_coo_ph_label = QtWidgets.QLabel(self.centralwidget)
        self.title_coo_ph_label.setGeometry(QtCore.QRect(110, 70, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.title_coo_ph_label.setFont(font)
        self.title_coo_ph_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_coo_ph_label.setObjectName("title_coo_ph_label")
        self.Y_m = QtWidgets.QLineEdit(self.centralwidget)
        self.Y_m.setGeometry(QtCore.QRect(220, 420, 81, 20))
        self.Y_m.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.Y_m.setAlignment(QtCore.Qt.AlignCenter)
        self.Y_m.setObjectName("Y_m")
        self.y_m = QtWidgets.QLineEdit(self.centralwidget)
        self.y_m.setGeometry(QtCore.QRect(460, 420, 81, 20))
        self.y_m.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.y_m.setAlignment(QtCore.Qt.AlignCenter)
        self.y_m.setObjectName("y_m")
        self.x_m = QtWidgets.QLineEdit(self.centralwidget)
        self.x_m.setGeometry(QtCore.QRect(360, 420, 81, 20))
        self.x_m.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.x_m.setAlignment(QtCore.Qt.AlignCenter)
        self.x_m.setObjectName("x_m")
        self.X_m = QtWidgets.QLineEdit(self.centralwidget)
        self.X_m.setGeometry(QtCore.QRect(120, 420, 81, 20))
        self.X_m.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.X_m.setAlignment(QtCore.Qt.AlignCenter)
        self.X_m.setObjectName("X_m")
        self.Y_m_label = QtWidgets.QLabel(self.centralwidget)
        self.Y_m_label.setGeometry(QtCore.QRect(250, 400, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Y_m_label.setFont(font)
        self.Y_m_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Y_m_label.setObjectName("Y_m_label")
        self.X_m_label = QtWidgets.QLabel(self.centralwidget)
        self.X_m_label.setGeometry(QtCore.QRect(150, 400, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.X_m_label.setFont(font)
        self.X_m_label.setAlignment(QtCore.Qt.AlignCenter)
        self.X_m_label.setObjectName("X_m_label")
        self.y_m_label = QtWidgets.QLabel(self.centralwidget)
        self.y_m_label.setGeometry(QtCore.QRect(490, 400, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.y_m_label.setFont(font)
        self.y_m_label.setAlignment(QtCore.Qt.AlignCenter)
        self.y_m_label.setObjectName("y_m_label")
        self.x_m_label = QtWidgets.QLabel(self.centralwidget)
        self.x_m_label.setGeometry(QtCore.QRect(390, 400, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.x_m_label.setFont(font)
        self.x_m_label.setAlignment(QtCore.Qt.AlignCenter)
        self.x_m_label.setObjectName("x_m_label")
        self.btn_calcul_m = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calcul_m.setGeometry(QtCore.QRect(170, 460, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_calcul_m.setFont(font)
        self.btn_calcul_m.setStyleSheet("background-color: rgb(0, 155, 134);\n"
"color: rgb(255, 255, 255);")
        self.btn_calcul_m.setObjectName("btn_calcul_m")
        self.title_trans_label = QtWidgets.QLabel(self.centralwidget)
        self.title_trans_label.setGeometry(QtCore.QRect(750, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title_trans_label.setFont(font)
        self.title_trans_label.setObjectName("title_trans_label")
        self.title_proj_label = QtWidgets.QLabel(self.centralwidget)
        self.title_proj_label.setGeometry(QtCore.QRect(750, 140, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title_proj_label.setFont(font)
        self.title_proj_label.setObjectName("title_proj_label")
        self.system_img = QtWidgets.QLabel(self.centralwidget)
        self.system_img.setGeometry(QtCore.QRect(750, 180, 181, 121))
        font = QtGui.QFont()
        font.setFamily("Playfair Display Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.system_img.setFont(font)
        self.system_img.setText("")
        self.system_img.setPixmap(QtGui.QPixmap("images/projective equation.png"))
        self.system_img.setScaledContents(True)
        self.system_img.setObjectName("system_img")
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        self.info_label.setGeometry(QtCore.QRect(620, 410, 300, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.info_label.setFont(font)
        self.info_label.setStyleSheet("background-color: rgb(174, 188, 191);")
        self.info_label.setText("")
        self.info_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.info_label.setObjectName("info_label")
        self.info_icon = QtWidgets.QLabel(self.centralwidget)
        self.info_icon.setGeometry(QtCore.QRect(620, 360, 41, 41))
        self.info_icon.setText("")
        self.info_icon.setPixmap(QtGui.QPixmap("images/info-1.png"))
        self.info_icon.setScaledContents(True)
        self.info_icon.setObjectName("info_icon")
        self.title_coo_ph_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.title_coo_ph_label_2.setGeometry(QtCore.QRect(110, 90, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.title_coo_ph_label_2.setFont(font)
        self.title_coo_ph_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_coo_ph_label_2.setObjectName("title_coo_ph_label_2")
        self.title_coo_ph_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.title_coo_ph_label_3.setGeometry(QtCore.QRect(340, 90, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.title_coo_ph_label_3.setFont(font)
        self.title_coo_ph_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.title_coo_ph_label_3.setObjectName("title_coo_ph_label_3")
        self.title_coo_ph_label_4 = QtWidgets.QLabel(self.centralwidget)
        self.title_coo_ph_label_4.setGeometry(QtCore.QRect(340, 70, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.title_coo_ph_label_4.setFont(font)
        self.title_coo_ph_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.title_coo_ph_label_4.setObjectName("title_coo_ph_label_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(110, 130, 441, 131))
        self.frame.setStyleSheet("background-color: rgb(239, 168, 144);")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Y1 = QtWidgets.QLineEdit(self.frame)
        self.Y1.setGeometry(QtCore.QRect(350, 10, 81, 20))
        self.Y1.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.Y1.setAlignment(QtCore.Qt.AlignCenter)
        self.Y1.setObjectName("Y1")
        self.y2 = QtWidgets.QLineEdit(self.frame)
        self.y2.setGeometry(QtCore.QRect(110, 40, 81, 20))
        self.y2.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.y2.setAlignment(QtCore.Qt.AlignCenter)
        self.y2.setObjectName("y2")
        self.Y2 = QtWidgets.QLineEdit(self.frame)
        self.Y2.setGeometry(QtCore.QRect(350, 40, 81, 20))
        self.Y2.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.Y2.setAlignment(QtCore.Qt.AlignCenter)
        self.Y2.setObjectName("Y2")
        self.Y3 = QtWidgets.QLineEdit(self.frame)
        self.Y3.setGeometry(QtCore.QRect(350, 70, 81, 20))
        self.Y3.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.Y3.setAlignment(QtCore.Qt.AlignCenter)
        self.Y3.setObjectName("Y3")
        self.x4 = QtWidgets.QLineEdit(self.frame)
        self.x4.setGeometry(QtCore.QRect(10, 100, 81, 20))
        self.x4.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.x4.setAlignment(QtCore.Qt.AlignCenter)
        self.x4.setObjectName("x4")
        self.y1 = QtWidgets.QLineEdit(self.frame)
        self.y1.setGeometry(QtCore.QRect(110, 10, 81, 20))
        self.y1.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.y1.setAlignment(QtCore.Qt.AlignCenter)
        self.y1.setObjectName("y1")
        self.x2 = QtWidgets.QLineEdit(self.frame)
        self.x2.setGeometry(QtCore.QRect(10, 40, 81, 20))
        self.x2.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.x2.setAlignment(QtCore.Qt.AlignCenter)
        self.x2.setObjectName("x2")
        self.Y4 = QtWidgets.QLineEdit(self.frame)
        self.Y4.setGeometry(QtCore.QRect(350, 100, 81, 20))
        self.Y4.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.Y4.setAlignment(QtCore.Qt.AlignCenter)
        self.Y4.setObjectName("Y4")
        self.X4 = QtWidgets.QLineEdit(self.frame)
        self.X4.setGeometry(QtCore.QRect(250, 100, 81, 20))
        self.X4.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.X4.setAlignment(QtCore.Qt.AlignCenter)
        self.X4.setObjectName("X4")
        self.x3 = QtWidgets.QLineEdit(self.frame)
        self.x3.setGeometry(QtCore.QRect(10, 70, 81, 20))
        self.x3.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.x3.setAlignment(QtCore.Qt.AlignCenter)
        self.x3.setObjectName("x3")
        self.x1 = QtWidgets.QLineEdit(self.frame)
        self.x1.setGeometry(QtCore.QRect(10, 10, 81, 20))
        self.x1.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.x1.setAlignment(QtCore.Qt.AlignCenter)
        self.x1.setObjectName("x1")
        self.X2 = QtWidgets.QLineEdit(self.frame)
        self.X2.setGeometry(QtCore.QRect(250, 40, 81, 20))
        self.X2.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.X2.setAlignment(QtCore.Qt.AlignCenter)
        self.X2.setObjectName("X2")
        self.X3 = QtWidgets.QLineEdit(self.frame)
        self.X3.setGeometry(QtCore.QRect(250, 70, 81, 20))
        self.X3.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.X3.setAlignment(QtCore.Qt.AlignCenter)
        self.X3.setObjectName("X3")
        self.y3 = QtWidgets.QLineEdit(self.frame)
        self.y3.setGeometry(QtCore.QRect(110, 70, 81, 20))
        self.y3.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.y3.setAlignment(QtCore.Qt.AlignCenter)
        self.y3.setObjectName("y3")
        self.y4 = QtWidgets.QLineEdit(self.frame)
        self.y4.setGeometry(QtCore.QRect(110, 100, 81, 20))
        self.y4.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.y4.setAlignment(QtCore.Qt.AlignCenter)
        self.y4.setObjectName("y4")
        self.X1 = QtWidgets.QLineEdit(self.frame)
        self.X1.setGeometry(QtCore.QRect(250, 10, 81, 20))
        self.X1.setStyleSheet("background-color: rgb(222, 232, 233);")
        self.X1.setAlignment(QtCore.Qt.AlignCenter)
        self.X1.setObjectName("X1")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(660, 79, 81, 261))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.a1 = QtWidgets.QLineEdit(self.frame_2)
        self.a1.setStyleSheet("background-color: rgb(144, 187, 243);")
        self.a1.setAlignment(QtCore.Qt.AlignCenter)
        self.a1.setObjectName("a1")
        self.verticalLayout.addWidget(self.a1)
        self.b1 = QtWidgets.QLineEdit(self.frame_2)
        self.b1.setStyleSheet("background-color: rgb(144, 187, 243);")
        self.b1.setAlignment(QtCore.Qt.AlignCenter)
        self.b1.setObjectName("b1")
        self.verticalLayout.addWidget(self.b1)
        self.c1 = QtWidgets.QLineEdit(self.frame_2)
        self.c1.setStyleSheet("background-color: rgb(144, 187, 243);")
        self.c1.setAlignment(QtCore.Qt.AlignCenter)
        self.c1.setObjectName("c1")
        self.verticalLayout.addWidget(self.c1)
        self.a4 = QtWidgets.QLineEdit(self.frame_2)
        self.a4.setStyleSheet("background-color: rgb(239, 168, 144);")
        self.a4.setAlignment(QtCore.Qt.AlignCenter)
        self.a4.setObjectName("a4")
        self.verticalLayout.addWidget(self.a4)
        self.b4 = QtWidgets.QLineEdit(self.frame_2)
        self.b4.setStyleSheet("background-color: rgb(239, 168, 144);")
        self.b4.setAlignment(QtCore.Qt.AlignCenter)
        self.b4.setObjectName("b4")
        self.verticalLayout.addWidget(self.b4)
        self.a2 = QtWidgets.QLineEdit(self.frame_2)
        self.a2.setStyleSheet("background-color: rgb(242, 169, 169);")
        self.a2.setAlignment(QtCore.Qt.AlignCenter)
        self.a2.setObjectName("a2")
        self.verticalLayout.addWidget(self.a2)
        self.b2 = QtWidgets.QLineEdit(self.frame_2)
        self.b2.setStyleSheet("background-color: rgb(242, 169, 169);")
        self.b2.setAlignment(QtCore.Qt.AlignCenter)
        self.b2.setObjectName("b2")
        self.verticalLayout.addWidget(self.b2)
        self.c2 = QtWidgets.QLineEdit(self.frame_2)
        self.c2.setStyleSheet("background-color: rgb(242, 169, 169);")
        self.c2.setAlignment(QtCore.Qt.AlignCenter)
        self.c2.setObjectName("c2")
        self.verticalLayout.addWidget(self.c2)
        self.label_c2 = QtWidgets.QLabel(self.centralwidget)
        self.label_c2.setGeometry(QtCore.QRect(640, 300, 14, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_c2.setFont(font)
        self.label_c2.setStyleSheet("color: rgb(242, 65, 65);")
        self.label_c2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_c2.setObjectName("label_c2")
        self.label_a1 = QtWidgets.QLabel(self.centralwidget)
        self.label_a1.setGeometry(QtCore.QRect(640, 90, 14, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_a1.setFont(font)
        self.label_a1.setStyleSheet("color:rgb(45, 58, 76)")
        self.label_a1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a1.setObjectName("label_a1")
        self.label_b2 = QtWidgets.QLabel(self.centralwidget)
        self.label_b2.setGeometry(QtCore.QRect(640, 270, 14, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_b2.setFont(font)
        self.label_b2.setStyleSheet("color: rgb(242, 65, 65);")
        self.label_b2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b2.setObjectName("label_b2")
        self.label_a4 = QtWidgets.QLabel(self.centralwidget)
        self.label_a4.setGeometry(QtCore.QRect(640, 180, 14, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_a4.setFont(font)
        self.label_a4.setStyleSheet("color:rgb(91, 64, 55)")
        self.label_a4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a4.setObjectName("label_a4")
        self.label_b1 = QtWidgets.QLabel(self.centralwidget)
        self.label_b1.setGeometry(QtCore.QRect(640, 120, 14, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_b1.setFont(font)
        self.label_b1.setStyleSheet("color:rgb(45, 58, 76)")
        self.label_b1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b1.setObjectName("label_b1")
        self.label_b4 = QtWidgets.QLabel(self.centralwidget)
        self.label_b4.setGeometry(QtCore.QRect(640, 210, 14, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_b4.setFont(font)
        self.label_b4.setStyleSheet("color:rgb(91, 64, 55)")
        self.label_b4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b4.setObjectName("label_b4")
        self.label_c1 = QtWidgets.QLabel(self.centralwidget)
        self.label_c1.setGeometry(QtCore.QRect(640, 150, 14, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_c1.setFont(font)
        self.label_c1.setStyleSheet("color:rgb(45, 58, 76)")
        self.label_c1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_c1.setObjectName("label_c1")
        self.label_a2 = QtWidgets.QLabel(self.centralwidget)
        self.label_a2.setGeometry(QtCore.QRect(640, 240, 14, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_a2.setFont(font)
        self.label_a2.setStyleSheet("color: rgb(242, 65, 65);")
        self.label_a2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a2.setObjectName("label_a2")
        self.frame_2.raise_()
        self.frame.raise_()
        self.alert_icon.raise_()
        self.alert_message_label.raise_()
        self.point_1_label.raise_()
        self.point_2_label.raise_()
        self.point_3_label.raise_()
        self.point_4_label.raise_()
        self.x_point_label.raise_()
        self.y_point_label.raise_()
        self.X_point_label.raise_()
        self.Y_point_label.raise_()
        self.btn_calcul_coef.raise_()
        self.btn_remettre.raise_()
        self.label_1_m.raise_()
        self.label_2_m.raise_()
        self.point_m_label.raise_()
        self.title_coo_ph_label.raise_()
        self.Y_m.raise_()
        self.y_m.raise_()
        self.x_m.raise_()
        self.X_m.raise_()
        self.Y_m_label.raise_()
        self.X_m_label.raise_()
        self.y_m_label.raise_()
        self.x_m_label.raise_()
        self.btn_calcul_m.raise_()
        self.title_trans_label.raise_()
        self.title_proj_label.raise_()
        self.system_img.raise_()
        self.info_label.raise_()
        self.info_icon.raise_()
        self.title_coo_ph_label_2.raise_()
        self.title_coo_ph_label_3.raise_()
        self.title_coo_ph_label_4.raise_()
        self.label_c2.raise_()
        self.label_a1.raise_()
        self.label_b2.raise_()
        self.label_a4.raise_()
        self.label_b1.raise_()
        self.label_b4.raise_()
        self.label_c1.raise_()
        self.label_a2.raise_()
        Projective.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Projective)
        self.statusbar.setObjectName("statusbar")
        Projective.setStatusBar(self.statusbar)
        self.Y_m_label.setBuddy(self.Y_m)
        self.X_m_label.setBuddy(self.X_m)
        self.y_m_label.setBuddy(self.y_m)
        self.x_m_label.setBuddy(self.x_m)

        self.array = np.array([self.x1, self.x2, self.x3, self.x4, self.y1, self.y2, self.y3, self.y4,
                               self.X1, self.X2, self.X3, self.X4, self.Y1, self.Y2, self.Y3, self.Y4])

        self.retranslateUi(Projective)
        QtCore.QMetaObject.connectSlotsByName(Projective)
        Projective.setTabOrder(self.x1, self.y1)
        Projective.setTabOrder(self.y1, self.x2)
        Projective.setTabOrder(self.x2, self.y2)
        Projective.setTabOrder(self.y2, self.x3)
        Projective.setTabOrder(self.x3, self.y3)
        Projective.setTabOrder(self.y3, self.x4)
        Projective.setTabOrder(self.x4, self.y4)
        Projective.setTabOrder(self.y4, self.X1)
        Projective.setTabOrder(self.X1, self.Y1)
        Projective.setTabOrder(self.Y1, self.X2)
        Projective.setTabOrder(self.X2, self.Y2)
        Projective.setTabOrder(self.Y2, self.X3)
        Projective.setTabOrder(self.X3, self.Y3)
        Projective.setTabOrder(self.Y3, self.X4)
        Projective.setTabOrder(self.X4, self.Y4)
        Projective.setTabOrder(self.Y4, self.btn_calcul_coef)
        Projective.setTabOrder(self.btn_calcul_coef, self.btn_remettre)
        Projective.setTabOrder(self.btn_remettre, self.X_m)
        Projective.setTabOrder(self.X_m, self.Y_m)
        Projective.setTabOrder(self.Y_m, self.btn_calcul_m)
        
        
        

        self.btn_calcul_coef.clicked.connect(self.coefficients)
        self.btn_remettre.clicked.connect(self.clearEntries)
        self.btn_calcul_m.clicked.connect(self.pointM)

    def retranslateUi(self, Projective):
        _translate = QtCore.QCoreApplication.translate
        Projective.setWindowTitle(_translate("Projective", "Transformation projective"))
        self.alert_message_label.setText(_translate("Projective", "Il faut saisir toutes les coordonnées en mm !"))
        self.point_1_label.setText(_translate("Projective", "Point 1"))
        self.point_2_label.setText(_translate("Projective", "Point 2"))
        self.point_3_label.setText(_translate("Projective", "Point 3"))
        self.point_4_label.setText(_translate("Projective", "Point 4"))
        self.x_point_label.setText(_translate("Projective", "x"))
        self.y_point_label.setText(_translate("Projective", "y"))
        self.X_point_label.setText(_translate("Projective", "X"))
        self.Y_point_label.setText(_translate("Projective", "Y"))
        self.btn_calcul_coef.setText(_translate("Projective", "CALCUL DES COEFFICIENTS"))
        self.btn_remettre.setText(_translate("Projective", "REMETTRE A 0"))
        self.label_1_m.setText(_translate("Projective", "Après le calcul des coefficients, il suffit de saisir les coordonnées "))
        self.label_2_m.setText(_translate("Projective", "comparateurs (X, Y) d\'un point pour avoir ses coordonnées photographiques :"))
        self.point_m_label.setText(_translate("Projective", "Point M"))
        self.title_coo_ph_label.setText(_translate("Projective", "Coordonnées"))
        self.Y_m_label.setText(_translate("Projective", "Y"))
        self.X_m_label.setText(_translate("Projective", "X"))
        self.y_m_label.setText(_translate("Projective", "y"))
        self.x_m_label.setText(_translate("Projective", "x"))
        self.btn_calcul_m.setText(_translate("Projective", "CALCULER x ET y"))
        self.title_trans_label.setText(_translate("Projective", "Transformation"))
        self.title_proj_label.setText(_translate("Projective", "PROJECTIVE"))
        self.title_coo_ph_label_2.setText(_translate("Projective", "photographiques"))
        self.title_coo_ph_label_3.setText(_translate("Projective", "comparateurs"))
        self.title_coo_ph_label_4.setText(_translate("Projective", "Coordonnées"))
        self.label_c2.setText(_translate("Projective", "c2"))
        self.label_c2.adjustSize()
        self.label_a1.setText(_translate("Projective", "a1"))
        self.label_a1.adjustSize()
        self.label_b2.setText(_translate("Projective", "b2"))
        self.label_b2.adjustSize()
        self.label_a4.setText(_translate("Projective", "a4"))
        self.label_a4.adjustSize()
        self.label_b1.setText(_translate("Projective", "b1"))
        self.label_b1.adjustSize()
        self.label_b4.setText(_translate("Projective", "b4"))
        self.label_b4.adjustSize()
        self.label_c1.setText(_translate("Projective", "c1"))
        self.label_c1.adjustSize()
        self.label_a2.setText(_translate("Projective", "a2"))
        self.label_a2.adjustSize()

    def clearEntries(self):
        self.x1.clear()
        self.x2.clear()
        self.x3.clear()
        self.x4.clear()
        self.y1.clear()
        self.y2.clear()
        self.y3.clear()
        self.y4.clear()
        self.X1.clear()
        self.X2.clear()
        self.X3.clear()
        self.X4.clear()
        self.Y1.clear()
        self.Y2.clear()
        self.Y3.clear()
        self.Y4.clear()
        self.X_m.clear()
        self.Y_m.clear()
        self.x_m.clear()
        self.y_m.clear()
        self.a1.clear()
        self.b1.clear()
        self.c1.clear()
        self.a4.clear()
        self.b4.clear()
        self.a2.clear()
        self.b2.clear()
        self.c2.clear()

        self.P = np.zeros(8)
        self.info_label.clear()

    def coefficients(self):
        self.info_label.clear()
        trouve = False
        for coordinate in self.array:
            if coordinate.text() == '':
                self.info_label.setText('Attention ! Il y a des case vides !')
                trouve = True
                break
            if coordinate.text().count('.') > 1:
                self.info_label.setText("Vous avez utilisé plusieurs points !")
                trouve = True
                break
            if ',' in coordinate.text():
                self.info_label.setText("Utilisez le (.) au lieu de la (,) !")
                trouve = True
                break

            for y in coordinate.text():
                if not (y.isnumeric()) and y!=',' and y!='.' :
                    self.info_label.setText("Vous n'avez pas saisi des nombres ")
                    trouve = True
                    break

        if trouve:
            pass
        else:
            self.matrixA()
            self.matrixB()

            try:
                X1 = np.linalg.inv((B.T) @ B)
                X2 = (B.T) @ A

                self.P = X1 @ X2

                self.a1.setText('%.4f' % self.P[0])
                self.b1.setText('%.4f' % self.P[1])
                self.c1.setText('%.4f' % self.P[2])
                self.a2.setText('%.4f' % self.P[3])
                self.b2.setText('%.4f' % self.P[4])
                self.c2.setText('%.4f' % self.P[5])
                self.a4.setText('%.4f' % self.P[6])
                self.b4.setText('%.4f' % self.P[-1])
            except:

                self.a1.clear()
                self.b1.clear()
                self.c1.clear()
                self.a4.clear()
                self.b4.clear()
                self.a2.clear()
                self.b2.clear()
                self.c2.clear()
                self.P= np.zeros(8)
                self.X_m.clear()
                self.Y_m.clear()
                self.x_m.clear()
                self.y_m.clear()
                self.info_label.setText('La transformation est invalide !')

    def pointM(self):
        trouve = False
        self.info_label.clear()
        if self.X_m.text() == '' or self.Y_m.text() == '':
            self.info_label.setText("Attention ! Il y a des case vides !")
            trouve = True

        if (',' in self.X_m.text()) or (',' in self.Y_m.text()):
            self.info_label.setText("Utilisez le (.) au lieu de la (,) !")
            trouve = True

        if (self.X_m.text().count('.') > 1) or (self.Y_m.text().count('.') > 1):
            self.info_label.setText("Vous avez utilisé plusieurs points !")
            trouve = True

        for element in self.X_m.text():
            if element.isalpha():
                self.info_label.setText("Vous avez saisi des lettres !")
                trouve = True
                break

        if not (trouve):
        
            temp = (self.P== np.zeros(8).all())
            if temp.all():
                self.info_label.setText("Il faut calculer les coefficients")
            else : 
                X = (self.P[0] * float(self.X_m.text()) + self.P[1] * float(self.Y_m.text()) + self.P[2]) / (
                    self.P[6] * float(self.X_m.text()) + self.P[-1] * float(self.Y_m.text()) + 1)
                Y = (self.P[3] * float(self.X_m.text()) + self.P[4] * float(self.Y_m.text()) + self.P[5]) / (
                    self.P[6] * float(self.X_m.text()) + self.P[-1] * float(self.Y_m.text()) + 1)
                self.x_m.setText('%.2f' % X)
                self.y_m.setText('%.2f' % Y)

            

    def matrixA(self):

        A[0] = float(self.x1.text())
        A[1] = float(self.x2.text())
        A[2] = float(self.x3.text())
        A[3] = float(self.x4.text())
        A[4] = float(self.y1.text())
        A[5] = float(self.y2.text())
        A[6] = float(self.y3.text())
        A[-1] = float(self.y4.text())

    def matrixB(self):
        # try:
        B[:4, :2] = np.array([[float(self.X1.text()), float(self.Y1.text())], [float(self.X2.text()), float(self.Y2.text())], [float(self.X3.text()), float(self.Y3.text())], [float(self.X4.text()), float(self.Y4.text())]])
        B[4:, 3:5] = np.array([[float(self.X1.text()), float(self.Y1.text())], [float(self.X2.text()), float(self.Y2.text())], [float(self.X3.text()), float(self.Y3.text())], [float(self.X4.text()), float(self.Y4.text())]])



        Ab11 = - (float(self.X1.text()) * float(self.x1.text()))
        Ab21 = - (float(self.X2.text()) * float(self.x2.text()))
        Ab31 = - (float(self.X3.text()) * float(self.x3.text()))
        Ab41 = - (float(self.X4.text()) * float(self.x4.text()))
        Ab51 = - (float(self.X1.text()) * float(self.y1.text()))
        Ab61 = - (float(self.X2.text()) * float(self.y2.text()))
        Ab71 = - (float(self.X3.text()) * float(self.y3.text()))
        Ab81 = - (float(self.X4.text()) * float(self.y4.text()))

        Ab12 = - (float(self.Y1.text()) * float(self.x1.text()))
        Ab22 = - (float(self.Y2.text()) * float(self.x2.text()))
        Ab32 = - (float(self.Y3.text()) * float(self.x3.text()))
        Ab42 = - (float(self.Y4.text()) * float(self.x4.text()))
        Ab52 = - (float(self.Y1.text()) * float(self.y1.text()))
        Ab62 = - (float(self.Y2.text()) * float(self.y2.text()))
        Ab72 = - (float(self.Y3.text()) * float(self.y3.text()))
        Ab82 = - (float(self.Y4.text()) * float(self.y4.text()))

        B[:, 6:] = np.array([[Ab11, Ab12], [Ab21, Ab22], [Ab31, Ab32], [Ab41, Ab42], [Ab51, Ab52], [Ab61, Ab62], [Ab71, Ab72], [Ab81, Ab82]])


